### ISSUE TITLE
Barra de búsqueda no está centrada en versión desktop

### ISSUE THREAD

**Issue by MarcosFlores178** [AgustinTorresOlivera/ProyectoDH-Agustin#1]
La parte superior del header debe tener este formato: 
logo alineado a la izquierda, barra de búsqueda centrada y a la derecha "Comprá en cuotas y sin tarjeta de crédito".

**Comment by AgustinTorresOlivera** [comment]
Resuelto gracias, me conecte tarde ahora vere el tuyo y te dejare algunos issues si noto algo
